version: '3.8'

services:
  video-stream-processor:
    build: ./services/video-stream-processor
    environment:
      - CAMERA_URLS=rtsp://camera1/stream,rtsp://camera2/stream
      - KNOWN_FACES_DIR=./data/faces
      - ENCODINGS_FILE=./data/encodings/known_face_encodings.pkl
      - STREAM_OUTPUT_URL=rtmp://streaming-service/live/stream
    volumes:
      - ./data/faces:/data/faces
      - ./data/encodings:/data/encodings

  streaming-service:
    build: ./services/streaming-service
    ports:
      - "1935:1935" # RTMP
      - "8080:8080" # HTTP for HLS
    volumes:
      - ./data/hls:/mnt/hls
