version: '3.8'

services:
  video-stream-processor:
    build:
      context: ../services/video-stream-processor
    volumes:
      - ../data:/app/data  # Mount the entire data directory
    depends_on:
      - streaming-service

  streaming-service:
    build:
      context: ../services/streaming-service
    ports:
      - "1935:1935" # RTMP
      - "8080:8080" # HTTP for HLS
    volumes:
      - ../data/hls:/mnt/hls  # This remains the same if the service directly uses the HLS directory

  ui:
    build:
      context: ../services/ui
    ports:
      - "80:80"
    depends_on:
      - streaming-service