version: '3.8'

services:
  video-stream-processor:
    build:
      context: ../services/video-stream-processor
      dockerfile: Dockerfile
    volumes:
      - ../services/video-stream-processor:/workspace:cached
      - ../data/faces:/workspace/faces:cached
    environment:
      CAMERA_URLS: "rtsp://camera1/stream,rtsp://camera2/stream"
      KNOWN_FACES_DIR: "/workspace/faces"
      ENCODINGS_FILE: "/workspace/faces/known_face_encodings.pkl"
      STREAM_OUTPUT_URL: "rtmp://localhost/live/stream"
  streaming-service:
    build:
      context: ../services/streaming-service
    ports:
      - "1935:1935" # RTMP
      - "8080:8080" # HTTP for HLS
  ui:
    build:
      context: ../services/ui
    ports:
      - "80:80"

volumes:
  hls: # This volume stores HLS video fragments
