version: '3.8'

services:
  video-stream-processor:
    build:
      context: ../services/video-stream-processor
    volumes:
      - ../data:/app/data
    depends_on:
      - streaming-service

  streaming-service:
    build:
      context: ../services/streaming-service
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ../data/hls:/mnt/hls 

  ui:
    build:
      context: ../services/ui
    ports:
      - "80:80"
    depends_on:
      - streaming-service