version: '3.8'

services:
  video-stream-ingestion:
    build:
      context: ./services/video-stream-ingestion
      dockerfile: Dockerfile
    volumes:
      - video-data:/data
    environment:
      CAMERA_SOURCE: "${CAMERA_SOURCE}"
    networks:
      - app_network

  facial-recognition:
    build:
      context: ./services/facial-recognition
      dockerfile: Dockerfile
    volumes:
      - video-data:/data
    depends_on:
      - video-stream-ingestion
    networks:
      - app_network

  database:
    image: nouchka/sqlite3
    volumes:
      - db-data:/root/db
    networks:
      - app_network

  ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - facial-recognition
    networks:
      - app_network

volumes:
  video-data:
  db-data:

networks:
  app_network:
