# Use an official Python runtime as a base image
FROM python:3.9-slim

# Install dependencies required for dlib
# Install FFmpeg, CMake, and build tools for dlib
RUN apt-get update && \
    apt-get install -y ffmpeg cmake build-essential && \
    rm -rf /var/lib/apt/lists/*


# Set the working directory in the container to /app/src
WORKDIR /app/src

# Copy only the necessary directories into the container
# Assuming your project structure includes src for source code and possibly other directories
COPY src/ ./
COPY requirements.txt /app/

# Move back to /app to install Python dependencies
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable
ENV NAME VideoStreamProcessor

# The command to run main.py
CMD ["python", "src/main.py"]
