# Use an official Python runtime as a base image
FROM python:3.9-slim

# Install FFmpeg for video processing
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
# Adjust if your app uses a different port (You may not need this for a processing service that doesn't serve HTTP content)
# EXPOSE 5000

# Define environment variable
ENV NAME VideoStreamProcessor

# Run main.py (or your main script name) when the container launches
CMD ["python", "main.py"]
